### ISSUE TITLE
Entrance and zone name improvement

### ISSUE THREAD

**Issue by matthewkirby** [brakkum/ZOoTR-Entrance-Tracker#3]
I love the tracker and use it extensively for our ER runs. That being said, I have a number of suggestions for renaming entrances. If you think that this is reasonable I can go ahead and make a PR with all of this.

Grotto Names
===
1. There is a single grotto in the tracker called "cow grotto". This, I assume, refers to the grotto that appears on Death Mountain Trail in vanilla. However, there is a second grotto that contains both a cow and a skulltula. I believe the intent is to mark this as a "Skulltula Grotto" on the tracker however this is then confused with the other Skulltula Grottos even though it also contains a cow. It might be good to make a new label for this specific grotto, "Cow and Skulltula Grotto", "Webbed grotto" or something similar.

2. Matching entrance names to the names that appear in the randomizer logic. The Hyrule Field grottos specifically always throw me off when marking the tracker. 

3. Changing "Royal Family's Tomb" to "Composer Grave" for consistency with randomizer and general usage.

House Names
===
1. As adult, Talon sleeps in a specific house and you need to interact with him to complete the full adult trading sequence. Currently, this falls under the classification, "House". Might want to split this off.

2. "Impa's House Cow" refers to the entrance to the cage containing the cow. Often, the front of the house is more convenient to access (or may be the only glitchless way of progressing!). It is probably worth renaming this to "Impa's House Cow Back" and then renaming one of the "House"s to "Impa's House Cow Front"

3. "Shooting Gallery" could be split into "Adult Shooting Gallery" and "Child Shooting Gallery".

**Comment by SlyryD** [comment]
https://github.com/brakkum/ZOoTR-Entrance-Tracker/pull/5
